<a href="https://colab.research.google.com/github/shallynagfase9/Linear-Regression-and-Logistic-Regression/blob/main/Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import load_iris

In [2]:
dataset = load_iris()

In [7]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [8]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [9]:
import pandas as pd
import numpy as np

In [10]:
df = pd.DataFrame(dataset.data, columns=dataset.feature_names)

In [11]:
df.head(4)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2

In [15]:
print(dataset.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [16]:
df["target"] = dataset.target

In [18]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [20]:
df['target'].unique()

array([0, 1, 2])

In [21]:
df['target']!=2

0       True
1       True
2       True
3       True
4       True
       ...  
145    False
146    False
147    False
148    False
149    False
Name: target, Length: 150, dtype: bool

In [22]:
df_copy = df[df['target']!=2]

In [23]:
df_copy.shape

(100, 5)

In [24]:
df_copy['target'].unique()

array([0, 1])

In [33]:
# Independent and dependent features
x= df_copy.iloc[:,:-1]
y= df_copy.iloc[:,-1]

In [34]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)

In [35]:
from sklearn.linear_model import LogisticRegression


In [36]:
classification = LogisticRegression(max_iter=200)

In [37]:
classification

LogisticRegression(max_iter=200)

In [38]:
classification.fit(x_train,y_train)

LogisticRegression(max_iter=200)

In [39]:
y_pred = classification.predict(x_test)

In [40]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

In [41]:
# Confusion Matrix, Accuracy, Classification report
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
print(confusion_matrix(y_test,y_pred)) # False positive is 0 and false negative is 0, so definately you'll get 100% accuracy

[[12  0]
 [ 0  8]]


In [42]:
print(accuracy_score(y_test,y_pred))

1.0


In [43]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



Cross-Validation


In [44]:
from sklearn.model_selection import KFold # KFold is a type  of Cross-Validation which provides average accuracy

In [45]:
cv = KFold(n_splits=5,shuffle=True)

In [46]:
cv

KFold(n_splits=5, random_state=None, shuffle=True)

In [47]:
from sklearn.model_selection import cross_val_score


In [51]:
## these are the scores all the cross validation
scores = cross_val_score(classification, x_train, y_train, scoring='accuracy',cv=cv)

In [52]:
scores

array([1., 1., 1., 1., 1.])

In [53]:
np.mean(scores) # average accuracy

1.0

In [55]:
## Lets see more complex data

# make a prediction with a multinomial logistic regression model
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
# define dataset (on your own)
x, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, random_state=1, n_classes=2)

In [57]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)

In [58]:
complex_class_model=LogisticRegression(max_iter=200)

In [60]:
complex_class_model.fit(x_train,y_train)

LogisticRegression(max_iter=200)

In [61]:
y_pred_complex=complex_class_model.predict(x_test)

In [62]:
print(confusion_matrix(y_test,y_pred_complex))
print(accuracy_score(y_test,y_pred_complex))
print(classification_report(y_test,y_pred_complex))

[[78 13]
 [29 80]]
0.79
              precision    recall  f1-score   support

           0       0.73      0.86      0.79        91
           1       0.86      0.73      0.79       109

    accuracy                           0.79       200
   macro avg       0.79      0.80      0.79       200
weighted avg       0.80      0.79      0.79       200



In [64]:
## Cross Validatiuon
cv=KFold(n_splits=5)
cross_val_score(complex_class_model,x_train,y_train,cv=cv)

array([0.80625, 0.78125, 0.79375, 0.8125 , 0.85625])